components:
  securitySchemes:
    default:
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes:
            SampleScope: sample scope description
          x-scopes-bindings:
            SampleScope: admin
      type: oauth2
info:
  title: SampleAPI
  version: "1.0"
openapi: 3.0.1
paths:
  /*:
    delete:
      responses:
        "200":
          description: OK
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
    get:
      responses:
        "200":
          description: OK
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
    patch:
      responses:
        "200":
          description: OK
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
    post:
      responses:
        "200":
          description: OK
      security:
      - default:
        - SampleScope
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
    put:
      responses:
        "200":
          description: OK
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
security:
- default: []
servers:
- url: /
